config/routes.rb
Rails.application.routes.draw do
  mount CarMarketplace::API => '/'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :cars
  resources :brands
  resources :dealers
  resources :models
  resources :favorites
  root "cars#index"
end

app/models/dealer.rb
class Dealer < ApplicationRecord
	has_many :cars

	validates :name, presence: true, uniqueness: true
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: %i[show edit update destroy]

  # GET /dealers or /dealers.json
  def index
    @dealers = Dealer.all
  end

  # GET /dealers/1 or /dealers/1.json
  def show
  end

  # GET /dealers/new
  def new
    @dealer = Dealer.new
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers or /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)

    respond_to do |format|
      if @dealer.save
        format.html { redirect_to dealer_url(@dealer), notice: "Dealer was successfully created." }
        format.json { render :show, status: :created, location: @dealer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealers/1 or /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        format.html { redirect_to dealer_url(@dealer), notice: "Dealer was successfully updated." }
        format.json { render :show, status: :ok, location: @dealer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1 or /dealers/1.json
  def destroy
    @dealer.destroy

    respond_to do |format|
      format.html { redirect_to dealers_url, notice: "Dealer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dealer_params
      params.require(:dealer).permit(:name)
    end
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/_dealer.html.erb
<% if current_user&.admin? %>
<div id="<%= dom_id dealer %>">
  <p>
    <strong>Name:</strong>
    <%= dealer.name %>
  </p>

</div>
<% end %>

app/views/dealers/_form.html.erb
<% if current_user&.admin? %>
<%= form_with(model: dealer) do |form| %>
  <div class="mb-3">
    <%= form.label :name, { class: "form-label"} %>
    <%= form.text_field :name, { class: "form-control", placeholder: "Name" } %>
  </div>
  <br><%= form.submit "Create Dealer", class: "btn btn-primary" %></br>
<% end %>
<% end %>

app/views/dealers/edit.html.erb
<% if current_user&.admin? %>
<h1>Editing dealer</h1>

<%= render "form", dealer: @dealer %>

<br>

<div>
  <%= link_to "Show this dealer", @dealer %> |
  <%= link_to "Back to dealers", dealers_path %>
</div>
<% end %>

app/views/dealers/index.html.erb
<% if current_user&.admin? %>
<%= button_to "New dealer", new_dealer_path, :id => 'open-contacts-dialog-btn',
class: 'btn btn-primary', :method => :get %>
<h1 class="mb-4">Dealers:</h1>
<div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
  <% @dealers.each do |dealer| %>
    <div class="col">
      <div class="card" style="width: 300px;">
        <h2 class="mb-4 card-header"><%= dealer.name %></h2>
        <div class="card-body">
            <%= button_to "Show this dealer", dealer, class: 'btn btn-secondary btn-sm', :method => :get %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/dealers/new.html.erb
<% if current_user&.admin? %>
<h1>New dealer</h1>

<%= render "form", dealer: @dealer %>

<br>

<div>
  <%= button_to "Back to dealers", dealers_path, class: 'btn btn-secondary btn-sm', :method => :get %>
</div>
<% end %>

app/views/dealers/show.html.erb
<% if current_user&.admin? %>
<div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
  <div class="col">
    <div class="card" style="width: 300px;">
      <h1 class="mb-4 card-header"><%= @dealer.name %></h1>
      <div class="card-body">
        <%= button_to "Edit", edit_dealer_path(@dealer), class: 'btn btn-secondary btn-sm', method: :get %>
        <%= link_to "Destroy", dealer_path(@dealer), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
        <%= link_to "Back to dealers", dealers_path, class: 'btn btn-secondary btn-sm' %>
      </div>
    </div>
  </div>
</div>
<% end %>