config/routes.rb
Rails.application.routes.draw do
  mount CarMarketplace::API => '/'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :cars
  resources :brands
  resources :dealers
  resources :models
  resources :favorites
  root "cars#index"
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :models, dependent: :destroy

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :set_brand, only: %i[show edit update destroy]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
    @brands = Brand.all
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.html.erb
<% if current_user&.admin? %>
<div id="<%= dom_id brand %>">
  <p>
    <strong>Name:</strong>
    <%= brand.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= brand.description %>
  </p>

</div>
<% end %>

app/views/brands/_form.html.erb
<% if current_user&.admin? %>
<%= form_with(model: brand) do |form| %>
  <div class="card">
    <div class="card-body">

    <div class="mb-3">
      <%= form.label :name, { class: "form-label"} %>
      <%= form.text_field :name, { class: "form-control", placeholder: "Name" } %>
    </div>

    <div class="field">
      <%= form.label :description, { class: "form-label"} %>
      <%= form.text_area :description, { class: "form-control", placeholder: "Description" } %>
    </div>
    <br><%= form.submit "Create Brand", class: "btn btn-primary" %></br>
  </div>
</div>
<% end %>
<% end %>

app/views/brands/edit.html.erb
<% if current_user&.admin? %>
<h1>Editing brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Show this brand", @brand %> |
  <%= link_to "Back to brands", brands_path %>
</div>
<% end %>

app/views/brands/index.html.erb
<% if current_user&.admin? %>
<%= button_to "New brand", new_brand_path, :id => 'open-contacts-dialog-btn',
class: 'btn btn-primary', :method => :get %>
<h1 class="mb-4">Brands:</h1>
<div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
  <% @brands.each do |brand| %>
    <div class="col">
      <div class="card" style="width: 300px;">
        <h2 class="mb-4 card-header"><%= brand.name %></h2>
        <div class="card-body">
            <%= button_to "Show this brand", brand, class: 'btn btn-secondary btn-sm', :method => :get %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/brands/new.html.erb
<% if current_user&.admin? %>
<h1>New brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= button_to "Back to brands", brands_path, class: 'btn btn-secondary btn-sm', :method => :get %>
</div>
<% end %>

app/views/brands/show.html.erb
<% if current_user&.admin? %>
<div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
  <div class="col">
    <div class="card" style="width: 300px;">
      <h1 class="mb-4 card-header">Brand:
        <%= @brand.name %></h1>
      <h2 class="mb-4 card-body">Description:
        <%= @brand.description %></h2>
      <div class="card-body">
        <%= button_to "Edit", edit_brand_path(@brand), class: 'btn btn-secondary btn-sm', method: :get %>
        <%= link_to "Destroy", brand_path(@brand), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
        <%= link_to "Back to brands", brands_path, class: 'btn btn-secondary btn-sm' %>
      </div>
    </div>
  </div>
</div>
<% end %>