config/routes.rb
Rails.application.routes.draw do
  mount CarMarketplace::API => '/'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :cars
  resources :brands
  resources :dealers
  resources :models
  resources :favorites
  root "cars#index"
end

app/models/car.rb
class Car < ApplicationRecord
  enum fueltype: { petrol: 0, diesel: 1 }
  enum bodytype: { micro: 0, sedan: 1, coupe: 2, suv: 3 }
  enum gearbox: { manual: 0, automatic: 1 }

  belongs_to :model, counter_cache: true
  belongs_to :dealer
  has_many :favorites, dependent: :destroy

  has_one_attached :photo
  validates :name, presence: true
  validates :fueltype, inclusion: { in: fueltypes.keys}
  validates :bodytype, inclusion: { in: bodytypes.keys}
  validates :gearbox, inclusion: { in: gearboxes.keys}
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_car, only: %i[show edit update destroy]

  def index
    @cars = Car.all
    @cars = @cars.where(fueltype: params[:fueltype]) if params[:fueltype].present?
    @cars = @cars.where(gearbox: params[:gearbox]) if params[:gearbox].present?
    @cars = @cars.where(bodytype: params[:bodytype]) if params[:bodytype].present?
    @cars = @cars.joins(model: :brand).where('brands.id = ?', params[:brand]) if params[:brand].present?
    @cars = @cars.where(price: params[:price_from]..) if params[:price_from].present?
    @cars = @cars.where('price <= ?', params[:price_to].to_f) if params[:price_to].present?
  end

  def show
    @fueltypes = Car.fueltypes.keys
    @bodytypes = Car.bodytypes.keys
    @gearboxes = Car.gearboxes.keys
  end

  def new
    @car = Car.new
    @brands = Brand.all
    @dealers = Dealer.all
    if params[:brand_id].present?
      @models = Model.where(brand_id: params[:brand_id])
    else
      @models = Model.all
    end

    respond_to do |format|
      format.html 
      format.json { render json: @models }
    end

    @fueltypes = Car.fueltypes.keys
    @bodytypes = Car.bodytypes.keys
    @gearboxes = Car.gearboxes.keys
  end

  def edit
    @brands = Brand.all
    @dealers = Dealer.all
    if params[:brand_id].present?
      @models = Model.where(brand_id: params[:brand_id])
    else
      @models = Model.all
    end
    @fueltypes = Car.fueltypes.keys
    @bodytypes = Car.bodytypes.keys
    @gearboxes = Car.gearboxes.keys
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.require(:car).permit(:name, :fueltype, :bodytype, :gearbox, :price, :photo, :model_id, :dealer_id,
                                  model_attributes: :brand_id)
    end
  end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <div class="col">
    <div class="card" style="max-width: 400px;">
      <% if car.photo.present? %>
        <%= image_tag car.photo, width: 300, class: 'd-block mx-auto', style: "object-fit: contain;" %>
      <% end %>
      <div class="card-body">
        <h5 class="mb-3"><%= link_to car.name, car_path(car), class: 'btn btn-secondary btn-sm', method: :get %></h5>
      </div>
    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <div class="mb-3">
    <div class="form-group">
      <%= form.label :name, { class: "form-label"} %>
      <%= form.text_field :name, { class: "form-control", placeholder: "Name" } %>
    </div>
  
    <div class="form-group">
      <%= form.label :fueltype, { class: "form-label"} %>
      <%= form.select :fueltype, @fueltypes %>
    </div>
  
    <div class="form-group">
      <%= form.label :bodytype, { class: "form-label"} %>
      <%= form.select :bodytype, @bodytypes, {} %>
    </div>
  
    <div class="form-group">
      <%= form.label :gearbox, { class: "form-label"} %>
      <%= form.select :gearbox, @gearboxes, {} %>
    </div>
  
    <div class="form-group">
      <%= form.label :price, { class: "form-label"} %>
      <%= form.number_field :price %>
    </div>
  
    <div class="form-group">
      <%= form.label :model_id, { class: "form-label"} %>
      <%= form.select :model_id, @models.map{ |m| [m.name, m.id] }, {}, id: "model_selector" %>
    </div>
  
    <div class="form-group">
      <%= form.label :dealer_id, { class: "form-label"} %>
      <%= form.select :dealer_id, @dealers.map{ |d| [d.name, d.id] } %>
    </div>
  
    <div class="form-group">
      <%= form.label :brand_ids, { class: "form-label"} %>
      <%= form.select :brand_ids, @brands.map{ |b| [b.name, b.id] }, {}, id: "brand_selector" %>
    </div>
  
    <div class='form-group'>
      <%= form.label :photo %>
      <%= form.file_field :photo %>
    </div>
  
    <div>
      <%= form.submit "Create car", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<% if current_user&.admin? %>
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>
<% end %>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>
  <%= form_tag(cars_path, method: :get, class: 'mb-5') do %>
    <div class='mb-3'>
      <div class="form-group p-1">
        <label class="mb-1">Fueltype:</label>
        <%= select_tag :fueltype, options_for_select({ all: nil }.merge(Car::fueltypes), params[:fueltype]), class: "form-control"%>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Gearbox:</label>
        <%= select_tag :gearbox, options_for_select({ all: nil }.merge(Car::gearboxes), params[:gearbox]), class: "form-control" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Bodytype:</label>
        <%= select_tag :bodytype, options_for_select({ all: nil }.merge(Car::bodytypes), params[:bodytype]), class: "form-control" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Price From:</label>
        <%= number_field_tag :price_from, params[:price_from], step: 0.01, class: "form-control" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Price To:</label>
        <%= number_field_tag :price_to, params[:price_to], step: 0.01, class: "form-control" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Brand:</label>
        <%= select_tag :brand, options_for_select({ all: nil }.merge(Brand.all.each_with_object({}) { |i, hash| hash[i.name] = i.id}), params[:brand]), class: "form-control" %>
      </div>
    <%= submit_tag 'Apply Filters' , name: nil, class: 'btn btn-secondary' %>
  <% end %>


<h1 class="text-center">Cars</h1>

<div id="cars">
  <div class="row">
  <% @cars.each do |car| %>
    <%= render car %>
  <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<% if current_user&.admin? %>
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>
<% end %>

app/views/cars/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <td><%= image_tag @car.photo, size: "450x600"%><td>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Configuration:</strong></td>
                <td><%= @car.name %></td>
              </tr>
              <tr>
                <td><strong>Model:</strong></td>
                <td><%= @car.model.name %></td>
              </tr>
              <tr>
                <td><strong>Brand:</strong></td>
                <td><%= @car.model.brand.name %></td>
              </tr>
              <tr>
                <td><strong>Cars count:</strong></td>
                <td><%= @car.model.cars.count %></td>
              </tr>
              <tr>
                <td><strong>Fueltupe:</strong></td>
                <td><%= @car.fueltype %></td>
              </tr>
              <tr>
                <td><strong>Bodytype:</strong></td>
                <td><%= @car.bodytype %></td>
              </tr>
              <tr>
                <td><strong>Gearbox:</strong></td>
                <td><%= @car.gearbox %></td>
              </tr>
              <tr>
                <td><strong>Price:</strong></td>
                <td><%= @car.price %></td>
              </tr>
              <tr>
                <td><strong>Dealer:</strong></td>
                <td><%= @car.dealer.name %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


<div>
  <% if current_user %>
    <% unless current_user.favorites.map(&:car_id).include?(@car.id) %>
      <br><%= button_to "Add to favorite", favorites_path(car_id: @car.id), method: :post, class: 'btn btn-secondary' %></br>
    <% else %>
      <br><%= button_to "Remove from favorites", favorite_path(car_id: @car.id), method: :delete %></br>
    <% end %>
  <% end %>
  <% if current_user&.admin? %>
  <%= button_to "Edit this car", edit_car_path(@car), class: 'btn btn-secondary', method: :get %>
  <%= button_to "Back to cars", cars_path, class: 'btn btn-secondary' %>

  <%= button_to "Destroy this car", @car, method: :delete, class: 'btn btn-secondary' %>
  <% end %>
</div>