config/routes.rb
Rails.application.routes.draw do
  mount CarMarketplace::API => '/'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :cars
  resources :brands
  resources :dealers
  resources :models
  resources :favorites
  root "cars#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><%= link_to "DreamCars", root_path %></div>
    </div>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li class="active"><%= link_to "Account", edit_user_registration_path %></li>
      <% end %>
      <% if current_user&.admin? %>
      <li class="active"><%= link_to "Brands", brands_path %></li>
      <li class="active"><%= link_to "Models", models_path %></li>
      <li class="active"><%= link_to "Dealers", dealers_path %></li>
      <li class="active"><%= link_to "Cars", new_car_path %></li>
      <% end %>
      <% if current_user %>
      <li class="active"><%= link_to "Favorites", favorites_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
     <% if current_user %>
      <li class="active"><%= link_to "Signout", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li class="active"><%= link_to "Signup", new_user_registration_path %></li>
      <li class="active"><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarMarketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_path 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert info") %>
    <% end %>
    <%= yield %>
  </body>
</html>